STORE RTRIM(WCLAVE) TO WCLAVE
STORE 0   TO WPAGINA
STORE 100 TO WLINEA
IF WSALIDA = 1
   STORE 20 TO WSALTO
   @ 0,0 CLEAR
ELSE
   SET DEVI TO PRINT
   STORE 55 TO WSALTO
ENDIF

SELECT MTCAT
GO TOP
DO WHILE .NOT. EOF()
   IF WCLAVE<>SPACE(LEN(WCLAVE)).AND.WCLAVE<>SUBSTR(CODCAT,1,LEN(WCLAVE))
      SELECT MTCAT
      SKIP
      LOOP
   ENDIF
   STORE WLINEA+1 TO WLINEA
   DO SALTO
   @ WLINEA,00  SAY CODCAT
   @ WLINEA,19  SAY DESCAT
   *@ WLINEA,54  SAY XXXX  PICTURE "@Z 999999999.99"
   SELECT MTCAT
   SKIP
ENDDO
IF WSALIDA=2
   SET DEVI TO SCRE
   EJECT
ELSE
   STORE "OPRIMA (Ù) PARA FINALIZAR" TO WTEXT
   STORE CHR(13) TO WCH
   DO PREGUNTA
   @ 0,0 CLEAR
ENDIF
RETURN
********************************************************************************
**********
PROC SALTO
**********
IF WLINEA >= WSALTO
   STORE WPAGINA + 1 TO WPAGINA
   IF WSALIDA=1 .AND. WPAGINA<>1
      STORE "OPRIMA (Ù) PARA CONTINUAR" TO WTEXT
      STORE CHR(13) TO WCH
      DO PREGUNTA
      @ 0,0 CLEAR
   ENDIF
   STORE 1 TO WLINEA
   IF WSALIDA=2
      @ 00,00  SAY CHR(14)+QQWW
   ELSE
      @ 00,00  SAY QQWW
   ENDIF
   @ 01,00 SAY "REPORTE DE CATEGORIAS"
   @ 01,70 SAY "Pag."+ALLTRIM(STR(WPAGINA,3))
   @ 03,00 SAY "CODIGO"
   @ 03,19 SAY "DESCRIPCION"
   @ 04,00 SAY REPLICATE("-",80)
   STORE 5 TO WLINEA
ENDIF
RETURN
